name: Generate Snake Game

on:
  workflow_dispatch:
  schedule:
    # This will make it run everyday at 00:00 UTC
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Snake Game
      uses: Platane/snk@v3
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          github-snake.svg
          github-snake-dark.svg?palette=github-dark
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
